using Domain;
using Generated_Clients.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Generated_Clients.Controllers
{
    /// <summary>
    /// Controller that demonstrates CRUD operations using Refit Generated Client
    /// All HTTP complexity is abstracted by the Refit interface
    /// The code is extremely clean and easy to maintain
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class CrudHttpClientController : ControllerBase
    {
        private readonly IJsonPlaceholderClient _jsonPlaceholderClient;

        /// <summary>
        /// Injects the IJsonPlaceholderClient automatically generated by Refit
        /// The implementation was created at runtime based on the interface
        /// </summary>
        public CrudHttpClientController(IJsonPlaceholderClient jsonPlaceholderClient)
        {
            _jsonPlaceholderClient = jsonPlaceholderClient;
        }

        /// <summary>
        /// Fetches all posts
        /// Refit handles the GET request and automatic deserialization
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            return Ok(await _jsonPlaceholderClient.GetAllAsync());
        }

        /// <summary>
        /// Creates a new post
        /// Refit automatically serializes the object to JSON
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Post(Post post)
        {
            return Ok(await _jsonPlaceholderClient.Post(post));
        }

        /// <summary>
        /// Updates an existing post
        /// Refit replaces {id} in the route with the parameter value
        /// </summary>
        [HttpPut]
        public async Task<IActionResult> Put(Post post)
        {
            return Ok(await _jsonPlaceholderClient.Put(post.Id, post));
        }

        /// <summary>
        /// Removes a post
        /// </summary>
        [HttpDelete]
        public async Task<IActionResult> Delete(int id = 2)
        {
            await _jsonPlaceholderClient.Delete(id);

            return Ok();
        }
    }
}