using Refit;
using Domain;
using Generated_Clients.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Generated_Clients.Controllers
{
    /// <summary>
    /// Controller that uses Refit Generated Client (IGitHubClient)
    /// The client implementation is automatically generated by Refit
    /// All HTTP code (serialization, requests, etc.) is abstracted
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class HttpClientController : ControllerBase
    {
        private readonly IGitHubClient _gitHubClient;

        /// <summary>
        /// Injects the IGitHubClient that was registered with AddRefitClient in Program.cs
        /// Refit automatically created a concrete implementation of this interface
        /// </summary>
        public HttpClientController(IGitHubClient gitHubClient)
        {
            _gitHubClient = gitHubClient;
        }

        public IEnumerable<GitHubBranch>? _GitHubBranches { get; set; }

        /// <summary>
        /// Fetches repository branches
        /// Refit handles all HTTP communication and deserialization
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            try
            {
                _GitHubBranches = await _gitHubClient.GetAspNetCoreDocsBranchesAsync();
            }
            catch (HttpRequestException)
            {
                // Re-throws the exception for error middleware handling
                throw;
            }
            return Ok(_GitHubBranches);
        }
    }
}